### ISSUE TITLE
Check multiplied CalDAV events via posteo.de

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#758]

**Comment by tibbi** [comment]
well every service does it a bit differently, but Google seems to be the most widely used by far. The issues that I could reproduce are already fixed, the rest will hopefully be fixed soon.

**Comment by DJCrashdummy** [comment]
well... the issue i'm suffering is also reproducible.  
if you need more details or other help, just ask for it.

**Comment by tibbi** [comment]
sure, some steps for reproducing could help. So if you modify a single instance of any recurring event and use NextCloud + DAVDroid that modified event instance multiplies?

**Comment by tibbi** [comment]
should be fixed in 6.2.2

**Comment by DJCrashdummy** [comment]
sorry @tibbi, i was pretty busy at work, hadn't any time to check this issue and still use some other calendar app (because of this bug). :slightly_frowning_face: 

unfortunately this bug even still persists in 6.5.1!

> So if you modify a single instance of any recurring event and use NextCloud + DAVDroid that modified event instance multiplies?

yes, every time i manually *"Refresh CalDAV calendars"* another instance occurs. - even some other apps on the same device (and therefore with exact the same setup) shows everything correct... so definitively a *Simple Calendar* issue.

have you reproduced this error and it works for you, or/and do you need some more resp. more exact information? (please be clement if it takes me longer to respond... but sooner or later i will. :wink:)

**Comment by JohnBrodie** [comment]
Just another datapoint, I have a Moto x4 running davx5, pulling multiple calendars from NextCloud (v 20.0.7) and am having the same issue. Using the latest version of Simple Calendar Pro from FDroid, there were 100+ of the same event (one in the past) by a day or two later. Affected many different events, deleting some of the duplicates works but they appear to come back after some time

If there's a more appropriate issue to put this in or if you need more info, let me know and I'll see what I can do.
